#pragma once
//This code was generated by QTWidgets, not by me, Scott Hodes
#include <QtWidgets/QMainWindow>
#include "ui_AERSP424_QT_Course_Project.h"

class AERSP424_QT_Course_Project : public QMainWindow
{
    Q_OBJECT

public:
    AERSP424_QT_Course_Project(QWidget *parent = nullptr);
    ~AERSP424_QT_Course_Project();

private:
    Ui::AERSP424_QT_Course_ProjectClass ui;
};
